name: orh_user_app_version1
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  swipe_cards: ^1.0.0
  unique_identifier: ^0.2.2
  crypto: ^3.0.1
  http: ^0.13.4
  get: ^4.6.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

