name: orh_user_app_version1
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  path_provider: ^2.0.9
  image_picker: ^0.8.4+11
  animator: ^3.1.0
  camera: ^0.9.4+16
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.5
  community_material_icon: ^5.9.55
  flutter_webrtc: ^0.7.0
  flutter_ion: ^1.0.0
  swipe_cards: ^1.0.0
  device_information: ^0.0.4
  unique_identifier: ^0.2.2

  crypto: ^3.0.1
  http: ^0.13.4
  get: ^4.6.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

