name: orh_user_app_version1
description: A new Flutter project.

publish_to:

version: 1.0.3+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  fl_chart: ^0.51.0
  syncfusion_flutter_charts: ^20.1.57
  intl: ^0.17.0
  crypto: ^3.0.2
  sqflite: ^2.0.2+1
  flutter_staggered_grid_view: ^0.6.1
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  path_provider: ^2.0.9
  image_picker: ^0.8.4+11
  animator: ^3.1.0
  camera: ^0.9.4+16
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.5
  community_material_icon: ^5.9.55
  flutter_webrtc: ^0.7.0
  flutter_ion: ^1.0.0
  swipe_cards: ^1.0.0
  device_information: ^0.0.4
  unique_identifier: ^0.2.2
  google_fonts: ^2.3.1
  http: ^0.13.4
  get: ^4.6.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/file/
    - assets/icon/

